export const increment = 'increment'
export const decrement = 'decrement'
export const reset = 'reset'
export const requestTodo = 'requestTodo'
export const successTodo = 'successTodo'
export const errorTodo = 'errorTodo'